### ISSUE TITLE
Remove debug info

### ISSUE THREAD

**Issue by RobertAudi** [jordwalke/VimSplitBalancer#1]
There is an [`echomsg` statement](https://github.com/jordwalke/VimSplitBalancer/blob/edb713d3d6428d80b508893c2870979ccb8d8430/plugin/VimSplitBalancer.vim#L60) that forces the "Press Enter ..." message before entering the a `NERDTree` buffer. I assume it's debug info but either way I believe it should be removed  :confused:

![screen shot 2016-12-03 at 11 12 46](https://cloud.githubusercontent.com/assets/87562/20858641/f9dd2464-b949-11e6-963f-61b8bf571fcd.png)

**Comment by RobertAudi** [comment]
Closing since #2 got merged. Thanks @jordwalke !

**Comment by jordwalke** [comment]
thank you!
